### PR TITLE
add restconf

### PR DESCRIPTION
**Pull request by vorburger**
@skitt any objection if I get this in already? It builds, wires lots of new things - just doesn't actually work yet :sweat_smile: (see commented out // GET in /restconf/modules/ in RestConfModuleTest), but unfortunately there are no errors in the log... could be just some small problem. Suggest to get this in and then debug it later.

### CODE REVIEW

**Comment by skitt** [comment]
> @skitt any objection if I get this in already? It builds, wires lots of new things - just doesn't actually work yet sweat_smile (see commented out // GET in /restconf/modules/ in RestConfModuleTest), but unfortunately there are no errors in the log... could be just some small problem. Suggest to get this in and then debug it later.

Merging this ties any further progress on simple to the resolution of the issue introduced here. I’d rather keep this as a PR for now (which can be worked on since it exists as a separate branch).

**Comment by vorburger** [comment]
> Merging this ties any further progress on simple to the resolution of the issue introduced here

not sure I understand how so, but sure.

BTW To anyone having a closer look at this #51 had a similiar test for Neutron which passes, so basic Web API stuff set up etc. should all be fiMerging this ties any further progress on simple to the resolution of the issue introduced herene; it seems to me that for somre reasons restconf is NOK here.

**Comment by vorburger** [comment]
@skitt we now have working restconf, how cool is that? Hopefully no objection if I merge this now?

**Comment by vorburger** [comment]
@skitt you may have missed this (10 tens ago); I've just rebased it - OK for you if I get this in today?

**Pull request merged**
